apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exporter
  labels:
    app: exporter
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: exporter
        tier: backend
    spec:
      containers:
      - name: exporter
        image: eu.gcr.io/pantel-2decb/exporter:v2.1
        ports:
        - containerPort: 8080
