version: 2
jobs:
  deploy:

    working_directory: ~/repo

    docker:
    - image: praqma/helmsman:v1.4.0-rc-helm-v2.8.1

    steps:
      - checkout
      - run:
          name: deploy utilities to the dev cluster
          command: |
            helmsman --debug --apply -f .circleci/helmsman-dev-deployment.toml

workflows:
  version: 2
  deploy-utilities:
    jobs:
    - deploy:
        filters:
          branches:
            only:
            - helmsman-utilities
