version: 2
jobs:
  build:
    docker:
      - image: azul/zulu-openjdk:8

    steps:
      - checkout

#    - restore_cache:
#        keys:
#          - gradle-cache
#    - run:
#        name: download codacy jar file
#        command: wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.1/codacy-coverage-reporter-4.0.1-assembly.jar

    - run:
        name: build entire repo
        # command: ./gradlew clean client-api:build --debug
        command: ./gradlew clean build

#    - setup_remote_docker

#    - save_cache:
#        key: gradle-cache
#        paths:
#        - "~/.gradle/caches"

workflows:
  version: 2
  build-repo-and-deploy:
    jobs:
      - build
          filters:
            branches:
              only: feature/circleci-integration
