version: 2
jobs:
  build:
    docker:
      - image: azul/zulu-openjdk:8

    steps:
      - checkout
      - run:
          name: build entire repo
          # command: ./gradlew clean client-api:build --debug
          command: ./gradlew clean build

workflows:
  version: 2
  build-repo-and-deploy:
    jobs:
      - build
          filters:
            branches:
              only: feature/circleci-integration
