version: 2
jobs:
  build:
    docker:
      # - image: azul/zulu-openjdk:8
      - image: circleci/openjdk:8u171-jdk

    steps:
      - checkout
      - run:
          name: Build entire repo, skipping test(s)
          # command: ./gradlew clean client-api:build --debug
          # command: ./gradlew clean client-api:build  -x test 
          command: ./gradlew clean build  -x test --parallel
  coverage-report:
    docker:
      - image: circleci/openjdk:8u171-jdk
    environment:
      CODACY_DOWNLOAD_URL: https://github.com/codacy/codacy-coverage-reporter/releases/download/ 
      CODACY_VERSION: 4.0.1
      CODACY_JAR_FILE: codacy-coverage-reporter-assembly-latest.jar
      CODACY_MODULE: com.codacy.CodacyCoverageReporter
    steps:
      - run:  
          name: Download codacy
          command: |
            wget -O ~/${CODACY_JAR_FILE} \
              ${CODACY_DOWNLOAD_URL}/${CODACY_VERSION}/codacy-coverage-reporter-${CODACY_VERSION}-assembly.jar

      - run:
          name: Generate Codacy code-coverage report
          command: |
            java -cp ~/${CODACY_JAR_FILE} ${CODACY_MODULE} report -l Java -r \
              analytics/build/reports/jacoco/test/jacocoTestReport.xml --partial
            java -cp ~/${CODACY_JAR_FILE} ${CODACY_MODULE} report -l Java -r \
              client-api/build/reports/jacoco/test/jacocoTestReport.xml --partial
            java -cp ~/${CODACY_JAR_FILE} ${CODACY_MODULE} report -l Java -r \
              diameter-stack/build/reports/jacoco/test/jacocoTestReport.xml --partial
            java -cp ~/${CODACY_JAR_FILE} ${CODACY_MODULE} report -l Java -r \
              embedded-graph-store/build/reports/jacoco/test/jacocoTestReport.xml --partial
            java -cp ~/${CODACY_JAR_FILE} ${CODACY_MODULE} report -l Java -r \
              ocs/build/reports/jacoco/test/jacocoTestReport.xml --partial
            java -cp ~/${CODACY_JAR_FILE} ${CODACY_MODULE} report -l Java -r \
              ocsgw/build/reports/jacoco/test/jacocoTestReport.xml --partial
            java -cp ~/${CODACY_JAR_FILE} ${CODACY_MODULE} report -l Java -r \
              ostelco-lib/build/reports/jacoco/test/jacocoTestReport.xml --partial
            java -cp ~/${CODACY_JAR_FILE} ${CODACY_MODULE} report -l Java -r \
              pseudonym-server/build/reports/jacoco/test/jacocoTestReport.xml --partial
            java -cp ~/${CODACY_JAR_FILE} ${CODACY_MODULE} final


workflows:
  version: 2
  build-repo-and-code-coverage:
    jobs:
      - build:
          filters:
            branches:
              only: feature/circleci-integration
      - coverage-report:
          requires:
            - build

