# DEV values for prime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
firebaseServiceAccount: ""
  

prime:
  image: eu.gcr.io/pi-ostelco-dev/prime
  tag: 2f47ab570
  pullPolicy: Always
  env: 
    FIREBASE_ROOT_PATH: dev_new
    NEO4J_HOST: neo4j-neo4j.neo4j.svc.cluster.local
    STRIPE_API_KEY: ""
  ports:
    - 8080
    - 8081
    - 8082 
    - 8083 
  resources: 
    limits:
      cpu: 200m
      memory: 350Mi
    requests:
      cpu: 100m
      memory: 200Mi  
  livenessProbe: {}
    # path: /
    # port: 8081
  readinessProbe: {}
    # path: /
    # port: 8081  
  annotations: 
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/prometheus-metrics'
    prometheus.io/port: '8081'  

esp:
  image: gcr.io/endpoints-release/endpoints-runtime
  tag: 1
  pullPolicy: IfNotPresent

ocsEsp: 
  enabled: true
  env: {}
  endpointAddress: ocs.new.dev.ostelco.org
  ports:
    - 9000
    - 8443
  

apiEsp: 
  enabled: true
  env: {}
  endpointAddress: api.new.dev.ostelco.org
  ports:
    - 9002
    - 443  

metricsEsp:
  enabled: true
  env: {}
  endpointAddress: metrics.new.dev.ostelco.org
  ports:
    - 9004
    - 9443
   

services:
  prime:
    name: prime-service
    type: LoadBalancer
    port: 443
    targetPort: 8443
    portName: grpc 
   # loadBalancerIP: x.y.z.n
  api:
    name: prime-api
    type: LoadBalancer
    port: 443
    targetPort: 443
    portName: https
    # loadBalancerIP: x.y.z.n
  metrics: 
    name: prime-metrics
    type: LoadBalancer
    port: 443
    targetPort: 9443  
    portName: grpc
    # loadBalancerIP: x.y.z.n

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - prime.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

certs: 
  enabled: true
  dnsProvider: dev-clouddns
  issuer: letsencrypt-production # or letsencrypt-staging
  apiDns: 
    - api.new.dev.ostelco.org
  ocsDns: 
    - ocs.new.dev.ostelco.org
  metricsDns: 
    - metrics.new.dev.ostelco.org

disruptionBudget: 
  enabled: false
  minAvailable: 1

nodeSelector: {}

tolerations: []

affinity: {}