version: "3.7"

services:
  neo4j-online-backup:
    container_name: neo4j-online-backup
    image: neo4j:3.4.7-enterprise
    command: >
      bin/neo4j-admin backup
      --backup-dir=/backup_dir
      --name=graph.db-backup
      --from=host.docker.internal
      --cc-report-dir=/backup_dir
    volumes:
    - "./backup_dir:/backup_dir"
    environment:
    - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes