version: "3.7"

services:
  neo4j-online-restore:
    container_name: neo4j-online-restore
    image: neo4j:3.4.7-enterprise
    command: >
      bin/neo4j-admin restore
      --from=/backup_dir/graph.db-backup
      --database=graph.db
      --force
    volumes:
    - "./backup_dir:/backup_dir"
    - "./data_dir:/data"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes